---
  - name: Add hosts to DNS
    hosts: lab-dns
    become: yes
    become_method: sudo
    tasks:
    - name: Add entry to lab-DNS superzone.com
      shell:
          "sudo sed -i -e '$asrv-ansible.superzone.com.          IN      A       192.168.100.5' /var/named/fwd.superzone.com && tail -1 /var/named/fwd.superzone.com"

    - name: Add entry to Primary DNS reverseZone 192.168.100
      shell:
          "sudo sed -i -e '$a5   IN      PTR     srv-ansible.superzone.com.' /var/named/rvs.superzone.com && tail -1 /var/named/rvs.superzone.com"

    - name: reboot service
      shell:
          "sudo systemctl restart named"