---
  - name: Install Prometheus on a VM
    hosts: Prometheus
    become: yes
    become_method: sudo
    tasks:
    - name: create directory /etc/prometheus
      shell:
          "sudo mkdir -p /etc/prometheus"

    - name: Add entry to lab-DNS superzone.com
      shell:
          "sudo mkdir -p /var/lib/prometheus"

    - name: Add entry to Primary DNS reverseZone 192.168.100
      shell:
          "sudo sed -i -e '$a6   IN      PTR     prometheus.superzone.com.    ; 192.168.100.6' /var/named/rvs.superzone.com && tail -1 /var/named/rvs.superzone.com"

    - name: Add entry to Primary DNS reverseZone 192.168.100
      shell:
          "sudo sed -i -e '$a7   IN      PTR     grafana.superzone.com.    ; 192.168.100.6' /var/named/rvs.superzone.com && tail -1 /var/named/rvs.superzone.com"

    - name: reboot service
      shell:
          "sudo systemctl restart named"
