---
  - name: Automate Install Prometheus
    hosts: monitoring
    become: yes
    become_method: sudo
    tasks:
    - name: 1 task
      shell:
          "sudo adduser -M -r -s /sbin/nologin prometheus"
    - name: 2 task
      shell:
          "sudo mkdir /etc/prometheus"
    - name: 3 task
      shell:
          "sudo mkdir /var/lib/prometheus"
    - name: 4 task
      shell:
          "cd /usr/src"
    - name: 5 task
      shell:
          "sudo wget https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz"
    - name: 6 task
      shell:
          "tar -xf prometheus-2.31.1.linux-amd64.tar.gz"
    - name: 7 task
      shell:
          "export $PROM_SRC=/usr/src/prometheus-*"
    - name: 8 task
      shell:
          "sudo cp $PROM_SRC/prometheus.yml /etc/prometheus/"
    - name: 9 task
      shell:
          "sudo cp $PROM_SRC/prometheus /usr/local/bin/"
    - name: 10 task
      shell:
          "sudo cp $PROM_SRC/promtool /usr/local/bin/"
    - name: 11 task
      shell:
          "sudo cp -r $PROM_SRC/consoles /etc/prometheus"
    - name: 12 task
      shell:
          "sudo cp -r $PROM_SRC/console_libraries /etc/prometheus"
    - name: 13 task
      shell:
          "sudo chown prometheus:prometheus /etc/prometheus"
    - name: 14 task
      shell:
          "sudo chown prometheus:prometheus /var/lib/prometheus"








#nano /etc/prometheus/prometheus.yml
#sudo nano /etc/prometheus/prometheus.yml
#sudo chown prometheus:prometheus /etc/prometheus
#sudo chown prometheus:prometheus /var/lib/prometheus
#sudo nano /etc/systemd/system/prometheus.service
#sudo systemctl daemon-reload
#sudo systemctl enable --now prometheus
#sudo systemctl status prometheus
#sudo firewall-cmd --permanent --add-service=9090/tcp
#sudo systemctl status firewalld.service
#sudo firewall-cmd --zone=public --add-port=443/tcp
#sudo firewall-cmd --runtime-to-permanent
#sudo firewall-cmd --list-services
#sudo firewall-cmd --zone=public --add-port=9090/tcp
#sudo firewall-cmd --runtime-to-permanent
#sudo firewall-cmd --list-services
#nano /usr/src/prometheus